### ISSUE TITLE
Permissions problem in tar generated by package

### ISSUE THREAD

**Issue by sathibault** [tmlbl/JVM.jl#5]
The Julia cp function does not seem to retain permissions.  Some shell scripts loose their execution bit.  I had to replace:

```
cp(".jdeps", "/tmp/.jdeps.pkg"; remove_destination=true)
```

with:

```
  run(`rm -rf /tmp/.jdeps.pkg`)
  run(`cp -r .jdeps /tmp/.jdeps.pkg`)
```

**Comment by tmlbl** [comment]
Good to know. I had thought Julia's cp would be more portable but apparently not. Making the change now.
