### ISSUE TITLE
JVM Init Error: realpath: command not found

### ISSUE THREAD

**Issue by lynnreave** [tmlbl/JVM.jl#6]
``` bash
jvm init
/usr/local/bin/jvm: line 10: realpath: command not found
mv: cannot stat '/root/.juliarc.jl': No such file or directory
ERROR: could not open file /test-project/init
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
mv: cannot stat '/root/.juliarc.jl.bak': No such file or directory
make: *** [.jdeps] Error 1
```

**Comment by lynnreave** [comment]
This seems to be with the latest code, using one of the build images we're using internally for Gitlab-CI. V1 works in these cases (and the build previously worked before, which was several weeks ago when it was built against the latest JVM in master (at least).

**Comment by Thecavepeanut** [comment]
hmm is your /test-project directory owned by root?  I believe all /.... directories are defaulted to root and you have to explicitly change it with chown, chmod, or a combo of chmod and chgrp. Which one depends on the environment you are building it for!
